---
title: async/await
order: 3
category:
  - 面试
---

[总结](https://segmentfault.com/a/1190000007535316)

## async 的作用

如果在函数中 return 一个直接量，async 会把这个直接量通过 Promise.resolve() 封装成 Promise 对象

## async/await 的注意点

- await 同一行后面应该跟着一个 Promise 对象，如果不是，需要转换（如果是常量会自动转换）
- await 同一行后面的内容对应 Promise 主体内容，即==同步执行的==
- await 下一行的内容对应 then()里面的内容，是==异步执行的==

## async/await 的优势

单一的 Promise 链并不能发现 async/await 的优势，但是，如果需要处理由多个 Promise 组成的 then 链的时候，优势就能体现出来了

```js
function takeLongTime(n) {
  return new Promise((resolve) => {
    setTimeout(() => resolve(n + 200), n);
  });
}

function step1(n) {
  console.log(`step1 with ${n}`);
  return takeLongTime(n);
}

function step2(n) {
  console.log(`step2 with ${n}`);
  return takeLongTime(n);
}

function step3(n) {
  console.log(`step3 with ${n}`);
  return takeLongTime(n);
}
```

> then 链的写法

```js
function doIt() {
  console.time("doIt");
  const time1 = 300;
  step1(time1)
    .then((time2) => step2(time2))
    .then((time3) => step3(time3))
    .then((result) => {
      console.log(`result is ${result}`);
      console.timeEnd("doIt");
    });
}

doIt();
```

> async/awiat 的写法

```js
async function doIt() {
  console.time("doIt");
  const time1 = 300;
  const time2 = await step1(time1);
  const time3 = await step2(time2);
  const result = await step3(time3);
  console.log(`result is ${result}`);
  console.timeEnd("doIt");
}

doIt();
```

## 手写 async/await

https://juejin.cn/post/7034323491369254942#heading-3

https://juejin.cn/post/6844904102053281806

async/await 是 generator 的语法糖,generator 生成器够让我们在函数执行时任意地方暂停(yield)，在后续遇到合适的时机需要使用这个函数时继续执行

generator 与 Promise 之间的区别：

1. generator 函数执行返回值不是 Promise，async 执行返回值是 Promise
2. generator 函数不支持自执行，需要执行相应的操作(next)，才能等同于 async 的排队效果

为了解决上述问题，封装一个高阶函数，接收一个 generator 函数，并且能让其进行自执行，返回一个具有 async 函数功能的函数

```js
function generatorToAsync(generatorFunc) {
  return function () {
    return new Promise((resolve, reject) => {});
  };
}
```

完整版：

```js
function asyncToGenerator(generatorFunc) {
  // 返回的是一个新的函数
  return function () {
    // 先调用generator函数 生成迭代器
    const gen = generatorFunc.apply(this, arguments);

    // 返回一个promise
    return new Promise((resolve, reject) => {
      // 内部定义一个step函数 用来一步一步的跨过yield的阻碍
      // key有next和throw两种取值，分别对应了gen的next和throw方法
      // arg参数则是用来把resolve的值交给下一个yield
      function step(key, arg) {
        let generatorResult;

        // 这个方法需要包裹在try catch中
        // 如果报错了 就把promise给reject掉 外部通过.catch可以获取到错误
        try {
          generatorResult = gen[key](arg);
        } catch (error) {
          return reject(error);
        }

        // gen.next() 得到的结果是一个 { value, done } 的结构
        const { value, done } = generatorResult;

        if (done) {
          // done是在最后一次调用next后才会为true
          // 这个value也就是generator函数最后的返回值
          return resolve(value);
        } else {
          // 除了最后结束的时候外，每次调用gen.next()，返回的是{ value: Promise, done: false } 的结构，
          // 这里要注意的是Promise.resolve可以接受一个promise为参数,并且这个promise参数被resolve的时候，这个then才会被调用
          return Promise.resolve(
            // 这个value对应的是yield后面的promise
            value
          ).then(
            // value这个promise被resove的时候，就会执行next,并且只要done不是true的时候 就会递归的往下解开promise
            function onResolve(val) {
              step("next", val);
            },
            // 如果promise被reject了 就再次进入step函数
            // 不同的是，这次的try catch中调用的是gen.throw(err)
            // 那么自然就被catch到 然后把promise给reject掉啦
            function onReject(err) {
              step("throw", err);
            }
          );
        }
      }
      step("next");
    });
  };
}
```
